-- ============================================================================
-- N-LIVE 결제없는 라이브 주문수집 시스템 — DB 마이그레이션 (멱등/재실행 안전)
-- 실행 위치: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 Run
-- 특징: 기존 테이블/데이터 변경 없음(추가만). 고객 주문은 SECURITY DEFINER RPC로만.
--       service_role 키 불필요 — anon(publishable) 키로 RPC만 호출.
-- ============================================================================

-- 0) 방송 세션 -----------------------------------------------------------------
create table if not exists public.live_sessions (
  id            bigint generated by default as identity primary key,
  seller        text not null,                 -- 담당 셀러(= orders.staff / customers.owner 규칙)
  slug          text not null,                 -- 셀러 고정 주소 (예: park-siyeon) → /shop/park-siyeon
  title         text,                          -- 방송 제목
  notice        text,                          -- 공지/배송·교환 정책
  status        text not null default 'draft', -- draft | open | closed
  ship_fee      int  not null default 4000,    -- 기본 배송비
  free_ship_min int  not null default 0,       -- 무료배송 기준(원). 0 = 무료배송 없음
  reserve_min   int  not null default 30,      -- 재고 가예약 시간(분)
  created_at    timestamptz not null default now(),
  opened_at     timestamptz,
  closed_at     timestamptz
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname='live_sessions_status_chk') then
    alter table public.live_sessions
      add constraint live_sessions_status_chk check (status in ('draft','open','closed')) not valid;
  end if;
end $$;
-- 한 셀러 동시 다중 open 방지 + 한 slug 동시 다중 open 방지(우선순위 명확화)
create unique index if not exists live_sessions_one_open_per_seller
  on public.live_sessions (seller) where status = 'open';
create unique index if not exists live_sessions_one_open_per_slug
  on public.live_sessions (slug) where status = 'open';
create index if not exists live_sessions_slug_idx on public.live_sessions (slug);

-- 1) 방송 상품 ----------------------------------------------------------------
create table if not exists public.session_products (
  id          bigint generated by default as identity primary key,
  session_id  bigint not null references public.live_sessions(id) on delete cascade,
  stock_code  text,                 -- ERP 품번(stock.code) 연결. null이면 캡처이미지 전용 상품
  name        text not null,        -- 방송 표시명
  live_price  int  not null,        -- 방송가(권위 있는 가격, 클라 전송값 무시)
  colors      text,                 -- 캡처전용 상품의 색상 목록(쉼표). 재고연결 상품은 stock에서 유도
  sizes       text,                 -- 캡처전용 상품의 사이즈 목록(쉼표)
  sort        int  not null default 0,      -- 노출 순서
  is_now      boolean not null default false,-- 지금 소개중
  active      boolean not null default true, -- 비활성/품절 숨김
  max_qty     int  not null default 0,       -- 최대 판매수량(0 = 제한없음)
  image_url   text,                 -- 방송 이미지(없으면 ERP 상품이미지 재사용)
  created_at  timestamptz not null default now()
);
create index if not exists session_products_session_idx on public.session_products (session_id);

-- 2) orders 추가 컬럼(전부 nullable, 기존 흐름 무영향) ---------------------------
alter table public.orders add column if not exists source                 text;         -- 'shop' = 링크주문
alter table public.orders add column if not exists session_id             bigint;       -- 담당 방송
alter table public.orders add column if not exists order_group_id         text;         -- 같은 장바구니 묶음
alter table public.orders add column if not exists reservation_expires_at  timestamptz;  -- 가예약 만료시각
alter table public.orders add column if not exists meta                    jsonb;        -- 닉네임/동의 등 부가
create index if not exists orders_group_idx   on public.orders (order_group_id);
create index if not exists orders_session_idx on public.orders (session_id);
create index if not exists orders_shop_resv_idx
  on public.orders (code, color, size)
  where source = 'shop' and pay = 'unpaid';

-- 3) 주문번호 시퀀스 -----------------------------------------------------------
create sequence if not exists public.live_order_seq;

-- 4) RLS: 내부 직원(authenticated)만 테이블 직접접근. 외부(anon)는 RPC 경유만 ------
alter table public.live_sessions   enable row level security;
alter table public.session_products enable row level security;

drop policy if exists ls_auth_all on public.live_sessions;
create policy ls_auth_all on public.live_sessions
  for all to authenticated using (true) with check (true);

drop policy if exists sp_auth_all on public.session_products;
create policy sp_auth_all on public.session_products
  for all to authenticated using (true) with check (true);
-- anon 정책 없음 → 두 테이블 직접조회/쓰기 불가(RLS 거부). 공개조회는 get_live_shop 경유.

grant select, insert, update, delete on public.live_sessions   to authenticated;
grant select, insert, update, delete on public.session_products to authenticated;
-- (identity 컬럼은 시퀀스 USAGE 권한 불필요 — Postgres가 내부 처리)

-- 5) 공개 조회 RPC: slug의 현재 open 방송 + 상품 + 옵션별 판매가능여부 -----------
--    SECURITY DEFINER → RLS 우회하되, 안전 필드만 노출(원가·전체재고·타고객 비공개)
create or replace function public.get_live_shop(p_slug text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s   public.live_sessions%rowtype;
  prods jsonb;
begin
  select * into s from public.live_sessions
   where slug = p_slug and status = 'open'
   order by opened_at desc nulls last, id desc limit 1;

  if not found then
    return jsonb_build_object('ok', true, 'status', 'closed');
  end if;

  select coalesce(jsonb_agg(p order by (p->>'sort')::int, (p->>'id')::bigint), '[]'::jsonb)
    into prods
  from (
    select jsonb_build_object(
      'id', sp.id,
      'name', sp.name,
      'live_price', sp.live_price,
      'image_url', sp.image_url,
      'is_now', sp.is_now,
      'sort', sp.sort,
      'max_qty', sp.max_qty,
      'linked', (sp.stock_code is not null),
      'options', case
        when sp.stock_code is not null then (
          -- 재고연결: stock에서 옵션 유도, (재고 - 미만료 가예약) > 0 이면 판매가능
          select coalesce(jsonb_agg(jsonb_build_object(
                   'color', st.color, 'size', st.size,
                   'available', (st.qty - coalesce(r.reserved,0)) > 0
                 ) order by st.color, st.size), '[]'::jsonb)
          from public.stock st
          left join lateral (
            select sum(o.qty) reserved from public.orders o
             where o.source='shop' and o.pay='unpaid'
               and o.reservation_expires_at > now()
               and o.code=st.code and o.color=st.color and o.size=st.size
          ) r on true
          where st.code = sp.stock_code
        )
        else (
          -- 캡처전용: 텍스트 옵션, 항상 판매가능
          select coalesce(jsonb_agg(jsonb_build_object(
                   'color', c, 'size', z, 'available', true)), '[]'::jsonb)
          from (select nullif(trim(c),'') c from unnest(string_to_array(coalesce(sp.colors,''), ',')) c) cc
          cross join (select nullif(trim(z),'') z from unnest(string_to_array(coalesce(sp.sizes,'')  , ',')) z) zz
        )
      end
    ) p
    from public.session_products sp
    where sp.session_id = s.id and sp.active = true
  ) q;

  return jsonb_build_object(
    'ok', true, 'status', 'open',
    'session', jsonb_build_object(
      'id', s.id, 'seller', s.seller, 'title', s.title,
      'notice', s.notice, 'ship_fee', s.ship_fee,
      'free_ship_min', s.free_ship_min, 'slug', s.slug
    ),
    'products', prods
  );
end $$;

-- 6) 주문 생성 RPC: 서버 권위 검증(가격·배송비·재고 재계산) + 고객매칭 + 가예약 ----
--    p_customer = {receiver, nick, phone, addr, addr_detail, zip, agree}
--    p_items    = [{product_id, color, size, qty}, ...]
create or replace function public.create_live_order(
  p_slug text, p_customer jsonb, p_items jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s          public.live_sessions%rowtype;
  it         jsonb;
  sp         public.session_products%rowtype;
  sku        public.stock%rowtype;
  reserved   int;
  sellable   int;
  qn         int;
  subtotal   int := 0;
  ship_fee   int := 0;
  grp        text;
  expires    timestamptz;
  cust_name  text;
  cust_id    bigint;
  phone_raw  text;
  phone_norm text;
  receiver   text;
  nick       text;
  full_addr  text;
  lines      jsonb := '[]'::jsonb;
begin
  -- 6-1) 방송 확인(권위: URL slug의 open 세션만. 클라 셀러명 신뢰 안 함)
  select * into s from public.live_sessions
   where slug = p_slug and status='open'
   order by opened_at desc nulls last, id desc limit 1;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'closed', 'msg', '방송이 종료되었거나 준비중입니다.');
  end if;

  -- 6-2) 필수 입력 검증
  receiver   := nullif(trim(coalesce(p_customer->>'receiver','')),'');
  nick       := nullif(trim(coalesce(p_customer->>'nick','')),'');
  phone_raw  := coalesce(p_customer->>'phone','');
  phone_norm := regexp_replace(phone_raw, '[^0-9]', '', 'g');
  full_addr  := trim(coalesce(p_customer->>'addr','') || ' ' || coalesce(p_customer->>'addr_detail',''));
  if receiver is null then return jsonb_build_object('ok',false,'reason','no_name','msg','받는 분 성함을 입력해 주세요.'); end if;
  if length(phone_norm) < 9 then return jsonb_build_object('ok',false,'reason','bad_phone','msg','휴대폰번호를 정확히 입력해 주세요.'); end if;
  if length(trim(full_addr)) < 4 then return jsonb_build_object('ok',false,'reason','no_addr','msg','배송지를 입력해 주세요.'); end if;
  if coalesce((p_customer->>'agree')::boolean, false) is not true then
    return jsonb_build_object('ok',false,'reason','no_agree','msg','개인정보 수집·구매 동의가 필요합니다.'); end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    return jsonb_build_object('ok',false,'reason','empty','msg','상품을 담아주세요.'); end if;

  -- 6-3) 상품별 서버 검증 + 재고 가예약 잠금
  for it in select * from jsonb_array_elements(p_items) loop
    select * into sp from public.session_products
      where id = (it->>'product_id')::bigint and session_id = s.id and active = true;
    if not found then
      return jsonb_build_object('ok',false,'reason','bad_item','msg','판매 중이 아닌 상품이 포함되어 있습니다.');
    end if;

    qn := greatest(1, coalesce((it->>'qty')::int, 1));
    if sp.max_qty > 0 and qn > sp.max_qty then qn := sp.max_qty; end if;

    if sp.stock_code is not null then
      -- 재고연결: 옵션 존재 + 판매가능 검증(동시성: stock 행 잠금으로 직렬화)
      select * into sku from public.stock
        where code = sp.stock_code
          and color = coalesce(it->>'color','') and size = coalesce(it->>'size','')
        for update;
      if not found then
        return jsonb_build_object('ok',false,'reason','bad_option','msg', sp.name || ' 옵션을 다시 선택해 주세요.');
      end if;
      select coalesce(sum(o.qty),0) into reserved from public.orders o
        where o.source='shop' and o.pay='unpaid' and o.reservation_expires_at > now()
          and o.code=sku.code and o.color=sku.color and o.size=sku.size;
      sellable := sku.qty - reserved;
      if qn > sellable then
        return jsonb_build_object('ok',false,'reason','soldout',
          'msg', sp.name || ' (' || coalesce(sku.color,'') || ' ' || coalesce(sku.size,'') || ') 재고가 부족합니다.');
      end if;
    end if;

    subtotal := subtotal + sp.live_price * qn;
    lines := lines || jsonb_build_object(
      'code',  coalesce(sp.stock_code, '방송상품'),
      'name',  sp.name,
      'tag',   case when sp.stock_code is not null then 'LIVE' else '캡처' end,
      'color', coalesce(it->>'color',''),
      'size',  coalesce(it->>'size',''),
      'qty',   qn,
      'price', sp.live_price
    );
  end loop;

  -- 6-4) 배송비 서버 재계산
  ship_fee := case when s.free_ship_min > 0 and subtotal >= s.free_ship_min then 0 else s.ship_fee end;

  -- 6-5) 고객 매칭(전화 우선) — 있으면 기존 이름 사용/미덮어씀, 없으면 신규등록
  select id, name into cust_id, cust_name from public.customers
    where regexp_replace(coalesce(phone,''), '[^0-9]', '', 'g') = phone_norm
    order by id limit 1;
  if not found then
    insert into public.customers(name, phone, addr, zip, owner, created_at)
      values (receiver, phone_raw, full_addr, nullif(p_customer->>'zip',''), s.seller, now())
      returning id, name into cust_id, cust_name;
  end if;

  -- 6-6) 주문번호 + 가예약 만료
  grp := 'NL-' || to_char(now() at time zone 'Asia/Seoul','YYMMDD')
         || '-' || lpad((nextval('public.live_order_seq') % 10000)::text, 4, '0');
  expires := now() + make_interval(mins => s.reserve_min);

  -- 6-7) 주문행 삽입(상품별 1행) — 재고 차감 안 함(가예약만). 입금확인 시 실차감.
  for it in select * from jsonb_array_elements(lines) loop
    insert into public.orders(
      order_date, staff, cust, phone, addr, code, item_name, tag, color, size, qty, price,
      pay, ship, back, source, session_id, order_group_id, reservation_expires_at, meta)
    values (
      (now() at time zone 'Asia/Seoul')::date, s.seller, cust_name, phone_raw, full_addr,
      it->>'code', it->>'name', it->>'tag', it->>'color', it->>'size',
      (it->>'qty')::int, (it->>'price')::int,
      'unpaid', 'miss', false, 'shop', s.id, grp, expires,
      jsonb_build_object('nick', nick, 'receiver', receiver, 'slug', s.slug));
  end loop;

  -- 6-8) 배송비 행(있을 때)
  if ship_fee > 0 then
    insert into public.orders(
      order_date, staff, cust, phone, addr, code, item_name, tag, color, size, qty, price,
      pay, ship, back, source, session_id, order_group_id, reservation_expires_at, meta)
    values (
      (now() at time zone 'Asia/Seoul')::date, s.seller, cust_name, phone_raw, full_addr,
      '배송비', '배송비', '배송비', '', '', 1, ship_fee,
      'unpaid', 'miss', false, 'shop', s.id, grp, expires,
      jsonb_build_object('nick', nick, 'receiver', receiver, 'slug', s.slug));
  end if;

  return jsonb_build_object(
    'ok', true, 'order_group_id', grp,
    'subtotal', subtotal, 'ship_fee', ship_fee, 'total', subtotal + ship_fee,
    'reserve_min', s.reserve_min, 'seller', s.seller);
end $$;

-- 7) 실행 권한: 공개조회+주문생성은 anon/authenticated 모두. 나머지는 최소권한 ------
revoke all on function public.get_live_shop(text)             from public;
revoke all on function public.create_live_order(text,jsonb,jsonb) from public;
grant execute on function public.get_live_shop(text)              to anon, authenticated;
grant execute on function public.create_live_order(text,jsonb,jsonb) to anon, authenticated;

-- 8) 방송 캡처 이미지 저장소(Storage) — 공개 읽기 / 직원(authenticated) 업로드 -----
insert into storage.buckets (id, name, public)
  values ('live','live', true)
  on conflict (id) do nothing;

drop policy if exists "live public read"  on storage.objects;
create policy "live public read" on storage.objects
  for select using (bucket_id = 'live');

drop policy if exists "live auth insert" on storage.objects;
create policy "live auth insert" on storage.objects
  for insert to authenticated with check (bucket_id = 'live');

drop policy if exists "live auth update" on storage.objects;
create policy "live auth update" on storage.objects
  for update to authenticated using (bucket_id = 'live') with check (bucket_id = 'live');

-- 끝. (재실행해도 안전)
